[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.gd"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan cache:clear"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"